### ISSUE TITLE
liburi-escape-perl missing when installing remotepi

### ISSUE THREAD

**Issue by pablo375** [subogero/remotepi#12]
Hi!

Thanks for sharing remotepi, it looks amazing. But in order to enjoy all its capabilities I should install it first. Problem comes when apt-get looks for liburi-escape-perl library, that seems not provided by your repo. In fact I've been trying to replace this library with no success since I haven't found any suitable candidate in the debian standard repos. I'm using Raspberry pi + model B, with Raspbian 7.5

Thanks in advance for your help!

**Comment by subogero** [comment]
I'll check in the evening, it's probably a typo in the deb package.

**Comment by subogero** [comment]
The package seems to be called `liburi-encode-perl`. Bowing my head in shame...

**Comment by pablo375** [comment]
Minor mistake. Anyway, how can I point to liburi-encode-perl instead of liburi-escape-perl?

Thanks.

**Comment by subogero** [comment]
I'm still investigating which is the right Debian package...

**Comment by subogero** [comment]
The wrong dependency `liburi-escape-perl` is actually in u2b, and it should be `liburi-perl`.

**Comment by subogero** [comment]
Opened u2b issue https://github.com/subogero/u2b/issues/1

**Comment by subogero** [comment]
Just uploaded u2b 0.2 to my package repo. Please try again.
