### ISSUE TITLE
How to synchronize different individual videos on slaves?

### ISSUE THREAD

**Issue by OMID-313** [subogero/remotepi#13]
Hi @subogero ,

I want to use 4 raspberry pi 2.0 boards to play 4 different videos via HDMI cables onto 4 TVs.

All I want is to play these individual videos in perfect synchronous mode.
Also, I want to use a master RPi to control these slave boards, and send some optional commands, like play, pause, next, previous, shut down, etc. (By using `omxd` probably.)
Besides, I want the whole system to start to play a group of videos in a directory, automatically after boot, and in an infinite loop. (By using `omxd A /home/pi/myfolder` in `rc.local` probably)

Would you please help me how I can implement such system?
How should I use the `remotepi` to be useful for this sync purpose?
Are there any other solutions you would suggest for such a system?

Your time and support would be highly appreciated.

**Comment by subogero** [comment]
Just a hint. On the command line of the master RPi

    curl -X POST -H 'Content-type: application/json' -d '{"cmd":"n"}' slave-raspberry-1/remotepi/S

will go to the next track on the other RPi called `slave-raspberry-1`.

**Comment by OMID-313** [comment]
Thank you very much @subogero for your hint. It is really helpful.

OK, now I know how to send commands like `play/pause` , `stop` , `next` , `previous` , etc. from master to slave. I just have to change `{"cmd":"n"}` to `{"cmd":"p"}` or `{"cmd":"N"}` or etc. That's OK.

Now a few more questions, if you don't mind:

1. How should I assign names for the slave boards? (So as to use their names like `slave-raspberry-1` when sending commands from the master.)
2. When sending commands from the master to the slaves, what should I do to send the commands to all the slaves at the same time? I mean, if I write the following on the master's terminal:

        curl -X POST -H 'Content-type: application/json' -d '{"cmd":"n"}' slave-raspberry-1/remotepi/S
        curl -X POST -H 'Content-type: application/json' -d '{"cmd":"n"}' slave-raspberry-2/remotepi/S
        curl -X POST -H 'Content-type: application/json' -d '{"cmd":"n"}' slave-raspberry-3/remotepi/S
        curl -X POST -H 'Content-type: application/json' -d '{"cmd":"n"}' slave-raspberry-4/remotepi/S
Then, the slave boards will have a very tiny difference in time, and they will be out of sync. How can I send these commands to the slaves at the same time?
3. In order to use this method (`remotepi` + `omxd`), is it enough to install `remotepi` only on the master? Or should I install it on all the boards, whether master or slaves?
4. How should I connect the master and the slave boards? Via Ethernet cables + Ethernet switch !?
5. Where shall I store each slave's video files? In its own storage? For example, if I use `{"cmd":"A /home/pi/my_folder"}` where will the slave look for? Its own directory or the master's directory?

Sorry for asking a lot of silly basic questions.
Thanks again for your great support.

**Comment by subogero** [comment]
1. You can set the hostname of each RPi in their `/etc/hostname` file. If you have a fairly intelligent router controlling your LAN, you'll be able to refer to each RPi by hostname instead of the IP address.

2. If you think about it, it's physically impossible to do it absolutely simultaneously, because the network packets to each RPI cannot go out at the same time on the same Ethernet cable. But you can decrease the delay if you don't wait for the completion of the `curl` commands to start the next. You can do that by starting them in the background, and then Linux will make sure the delay is as low as possible:

    curl -X POST -H 'Content-type: application/json' -d '{"cmd":"n"}' slave-raspberry-1/remotepi/S &
    curl -X POST -H 'Content-type: application/json' -d '{"cmd":"n"}' slave-raspberry-2/remotepi/S &
    curl -X POST -H 'Content-type: application/json' -d '{"cmd":"n"}' slave-raspberry-3/remotepi/S &
    curl -X POST -H 'Content-type: application/json' -d '{"cmd":"n"}' slave-raspberry-4/remotepi/S &
    jobs

The `&` at the end of each command starts them in the background, and `jobs` cleans up the zombies. Literally.

3. You need remotepi only on the slaves, if the master is not doing playback. But the master can do playback as well, in which case you should install `remotepi` everywhere. The master can control it's own `remotepi` by referring to it as `localhost

**Comment by OMID-313** [comment]
Thanks a billion @subogero for your detailed and very helpful reply. I do really really appreciate your time and great support. Thanks.

Well, now everything seems OK. I can't wait to receive my RPi 2 to test these features.

A few more questions (as always; sorry) :

1. Is it possible to set identical names for slave boards? If yes, then we can call all the slaves e.g. `slave-raspberry-1` , and then, by executing the following command:

        curl -X POST -H 'Content-type: application/json' -d '{"cmd":"n"}' slave-raspberry-1/remotepi/S &
all the slaves will get this command at the same time. Is this scenario correct? Besides, maybe it would be possible to send the command to a network _group_ instead of each host name, so all the slaves belonging to that group would receive the command at the same time. How about this?
2. Now I want to implement this system. As for the master, I will probably add the following codes to its `/etc/rc.local` file:

        curl -X POST -H 'Content-type: application/json' -d '{"cmd":"X"}' slave-raspberry-1/remotepi/S &
        curl -X POST -H 'Content-type: application/json' -d '{"cmd":"X"}' slave-raspberry-2/remotepi/S &
        curl -X POST -H 'Content-type: application/json' -d '{"cmd":"X"}' slave-raspberry-3/remotepi/S &
        curl -X POST -H 'Content-type: application/json' -d '{"cmd":"X"}' slave-raspberry-4/remotepi/S &
        curl -X POST -H 'Content-type: application/json' -d '{"cmd":"A /home/pi/my_folder"}' slave-raspberry-1/remotepi/S &
        curl -X POST -H 'Content-type: application/json' -d '{"cmd":"A /home/pi/my_folder"}' slave-raspberry-2/remotepi/S &
        curl -X POST -H 'Content-type: application/json' -d '{"cmd":"A /home/pi/my_folder"}' slave-raspberry-3/remotepi/S &
        curl -X POST -H 'Content-type: application/json' -d '{"cmd":"A /home/pi/my_folder"}' slave-raspberry-4/remotepi/S &
        jobs
so that they all reset the playlist at the beginning, and start to play the video files in loop.
Besides, I will edit the `lircrc` file of the master board to something like the following:

        begin
            prog = irexec
            button = Key_Next
            config = curl -X POST -H 'Content-type: application/json' -d '{"cmd":"n"}' slave-raspberry-1/remotepi/S &
        end
so that it can detect the IR remote controller, and send commands to the slaves. That seems OK. (Is it correct?) Now as for the slaves: this is the difficult part. How should I set the slaves to a _**always-ready-to-receive-commands**_ state? So that whenever commands are sent from the master to them, they receive it, execute it, and then become ready again for the next command?

Really sorry for asking so many questions.
Thanks again for your great help.

**Comment by subogero** [comment]
1. No, they must have different names. And sending HTTP requests to the LAN's broadcast IP is impossible too.

2. Don't put that curly stuff into `/etc/rc.local`. Put it in a separate shell script that takes 2 arguments, a `cmd` and a `file`. The you can call it with `foo X` and `foo A /home/pi/folder` in `/etc/rc.local`, but you can call it later any time to send any command to all the RPis. Just install `remotepi` on the slaves from my deb packages, from then on they just listen.

**Comment by subogero** [comment]
BTW, for an omxd command with a file, the JSON in the `curl` request is like this:

    {"cmd":"A","file":"/home/pi/folder"}
    {"cmd":"g","file":2}

**Comment by subogero** [comment]
Follow instructions on http://subogero.github.io/remotepi/ for `remotepi` installation.

**Comment by OMID-313** [comment]
Thanks again for your new hints. the `omxd` commands of the `JSON` are really handy.
The installation instructions are also very helpful. Thanks.

BTW, I didn't get your point about `foo`. Do you mean something like this in `/etc/rc.local`?

    /home/pi/my_script.sh

and in `my_script.sh` we have:

    curl -X POST -H 'Content-type: application/json' -d '{"cmd":"X"}' slave-raspberry-1/remotepi/S &
    curl -X POST -H 'Content-type: application/json' -d '{"cmd":"X"}' slave-raspberry-2/remotepi/S &
    curl -X POST -H 'Content-type: application/json' -d '{"cmd":"X"}' slave-raspberry-3/remotepi/S &
    curl -X POST -H 'Content-type: application/json' -d '{"cmd":"X"}' slave-raspberry-4/remotepi/S &
    curl -X POST -H 'Content-type: application/json' -d '{"cmd":"A /home/pi/my_folder"}' slave-raspberry-1/remotepi/S &
    curl -X POST -H 'Content-type: application/json' -d '{"cmd":"A /home/pi/my_folder"}' slave-raspberry-2/remotepi/S &
    curl -X POST -H 'Content-type: application/json' -d '{"cmd":"A /home/pi/my_folder"}' slave-raspberry-3/remotepi/S &
    curl -X POST -H 'Content-type: application/json' -d '{"cmd":"A /home/pi/my_folder"}' slave-raspberry-4/remotepi/S &
    jobs

Did you mean this !?

**Comment by subogero** [comment]
Sorry, how can I collect money from you for trivial Linux support? If I just answer all you questions it will 1) stop you from learning Linux on your own and 2) rob my time. If you want to do this kind of stuff with your RPi, you must learn Linux, including shell scripting etc. And please don't ask me how shall I learn Linux. The whole bloody internet is choke-full of the stuff. Is Google blocked in Iran? If so, you can use any other search engine.

**Comment by OMID-313** [comment]
You're right @subogero .
I'm really really sorry for asking every basic question here.
I shall try to learn linux very soon.

Thanks again for your time and all your helpful support.

**Comment by subogero** [comment]
Here is a script as a present, but please promise you'll look up and understand its details from the internet. Place it in a directory in the PATH, e.g. `/usr/local/bin`, call it `omxcluster` or whatever you like and call it like this:

    omxcluster g 2
    omxcluster p
    omxcluster A myfolder

Here is the contents:

    #!/bin/bash       
    if [ "$2" ]; then
        json='{"cmd":"'$1'","file":"'$2'"}'
    elif [ "$1" ]; then
        json='{"cmd":"'$1'"}'
    else
        echo 'Usage: omxcluster cmd [file]'
    fi
    cluster="slave1 slave2 slave3 slave4" # space-separated list of your slave RPis
    for node in $cluster; do
        curl -X POST -H 'Content-type: application/json' -d "$json" $node/remotepi/S &
    done       
    jobs

**Comment by OMID-313** [comment]
Thank you very much again @subogero for your great support.

Well, the script is rather self-explanatory and easy to understand.
Now I get your point about `foo` ;)

It seems that everything is OK. I just need to try them all to see how it works.
I can't wait to receive my RPi 2 and test all these stuff.

Thanks a lot for your time, help, and great support. :)

**Comment by OMID-313** [comment]
One little question, @subogero , if you don't mind:

As I remember from installing `omxd` a few month ago, it contained `omxplayer` in it, so I had to remove the raspbian's original `omxplayer` before installing `omxd`.
Is this also true with `remotepi` as well!?

Also, instead of raspbian, I'm trying to use a minimal distro like `Minibian` or `Moebius` or `Tiny-core-linux`, which don't have `omxplayer` installed by default. Now if I install `remotepi` following the instructions from here (http://subogero.github.io/remotepi/) , does it going to work well!? Or shall I install some other dependencies before?

Thanks again for your great support.

**Comment by subogero** [comment]
If you install `remotepi

**Comment by OMID-313** [comment]
Thanks @subogero for your answer.

I will try `remotepi` with `Minibian`.
That would be awesome :)

**Comment by subogero** [comment]
Comes `minibian` without a GUI? That would be awesome for me too.

**Comment by OMID-313** [comment]
Yes, `Minibian` has no GUI. That would be perfect.
Besides, `Moebius` is lighter than `Minibian` with half boot time.
Can we install `remotepi` easily on `Moebius` as well?
(If yes, that would be more awesome!)

**Comment by subogero** [comment]
I don't know Moebius, if it's Debian compatible, it should work.

**Comment by OMID-313** [comment]
Yes it is. It has been forked from `Raspbian`.

**Comment by OMID-313** [comment]
Well, in the installation guide of the `Moebius` (http://moebiuslinux.sourceforge.net/documentation/installation-guide/) they say: `... This is now a totally new distribution, is not based on debian anymore ...` . So it's not debian-based anymore. `Minibian` seems to be the reliable answer.

**Comment by OMID-313** [comment]
Another nice minimal distro (Debian-based) is `Diet-Pi` (http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=6).

**Comment by OMID-313** [comment]
Dear @subogero ,

I was wondering if maybe you could write an intro post for this question (about `remotepi`) :
http://raspberrypi.stackexchange.com/questions/32645/how-to-synchronize-multiple-video-displays
So that I can accept it as the best answer, and set the bounty for it.

This has 2 benefits:
1. I can thank you for all your help and support.
2. You can introduce `remotepi` more and more to people.

**Comment by subogero** [comment]
As you wish. This is a free world. :-)

**Comment by OMID-313** [comment]
So, I look forward to your answer there.

http://raspberrypi.stackexchange.com/questions/32645/how-to-synchronize-multiple-video-displays

Thanks :)

**Comment by OMID-313** [comment]
The bounty expires today, @subogero .
Would you please post an answer there? (based on all your comments here.)
http://raspberrypi.stackexchange.com/questions/32645/how-to-synchronize-multiple-video-displays
Thanks.
