### ISSUE TITLE
Web interface json requests return 400 errors

### ISSUE THREAD

**Issue by AbsoluteDestiny** [subogero/remotepi#14]
Failed to load resource: the server responded with a status of 400 (Malformed JSON Request):

GET http://192.168.1.215/remotepi/S1436643790320 400 (Malformed JSON Request)con.getStatus @ controls.js:33Tab.toggle @ controls.js:85con.browse @ controls.js:134(anonymous function) @ (index):97
controls.js:33 GET http://192.168.1.215/remotepi/S1436643790310 400 (Malformed JSON Request)con.getStatus @ controls.js:33(anonymous function) @ (index):17
controls.js:33 GET http://192.168.1.215/remotepi/S1436643792321 400 (Malformed JSON Request)con.getStatus @ controls.js:33(anonymous function) @ VM485:1
controls.js:33 GET http://192.168.1.215/remotepi/S1436643794323 400 (Malformed JSON Request)con.getStatus @ controls.js:33(anonymous function) @ VM486:1
raspberry.js:13 GET http://192.168.1.215/remotepi/home/ 400 (Malformed JSON Request)rpi.ls @ raspberry.js:13Tab.toggle @ controls.js:85con.browse @ controls.js:134onclick @ (index):20
controls.js:33 GET http://192.168.1.215/remotepi/S1436643796324 400 (Malformed JSON Request)

I installed on DietPi and Minibian
ran raspi-config to expand filesystem
followed the install instructions for the deb package
opened the url in a web browser but the pages have errors and no files are listed.

Youtube listing works intermittently but no videos play.

Is there a configuration issue with my setup? There is only the root account as a user right now so the home director is /root/

Is this a bug or a problem with my setup?

**Comment by subogero** [comment]
The funny thing is that the `400 Malformed JSON request` error should only happen with a POST request.

On the other hand, `remotepi` does assume that `/home` exists, which is probably wrong and I should fix it. Could you try creating `/home` and placing some files in it and try again?

**Comment by AbsoluteDestiny** [comment]
Doesn't appear to have made a difference in any way.

**Comment by subogero** [comment]
I'm planning to move to Minibian on my RPi2, so more testing will follow anyway. Sorry for the inconvenience. Is yours a PRi2?

**Comment by AbsoluteDestiny** [comment]
No, mine is an RPiB+ though I hope to get a 2 soon.

**Comment by subogero** [comment]
Mine is a B+ too, with Raspbian and the GUI removed manually

**Comment by subogero** [comment]
Oops, I just found a commit after the latest 1.4 version:

    commit 342b9f4524a03ce0b78615c386c098499cb8a936
    Author: Wouter Ellenbroek <wouterel@users.noreply.github.com>
    Date:   Fri May 15 20:41:05 2015 +0200
    Fixed bug that caused GET-requests to fail repeatedly after a previous malformed POST-request.

**Comment by subogero** [comment]
I must release a new version including the fix.

**Comment by subogero** [comment]
You could clone the repo, enter its directory and `make itest` as root. That way you could test the latest master branch.

**Comment by subogero** [comment]
Just released remotepi 1.5 with the fix. Installed it from the deb on a vanilla Minibian on RPi2, and I'm just watching some crazy KTM supermotard video on YouTube.

**Comment by subogero** [comment]
Closing issue, I hope 1.5 works for you too.
