### ISSUE TITLE
Youtube API

### ISSUE THREAD

**Issue by wouterel** [subogero/remotepi#9]
Youtube browsing as done by api.pl, using `https://gdata.youtube.com/feeds/api/videos?q=$query`, seems to have stopped working. I now only get one hit on any query which is a [video](https://www.youtube.com/watch?v=UKY3scPIMd8) about device support.
This appears to be the cause:
https://support.google.com/youtube/answer/6098135
Playing the video still works: `rpyt` is not affected.

**Comment by subogero** [comment]
Thanks for the hint, I wanted to fix this as well.

**Comment by subogero** [comment]
Confirmed, youtube-dl is still able to extract the stream URL from a give YouTube page.

**Comment by subogero** [comment]
BTW I'm writing a FAST YouTube search/download/playback utility. The v2 API just died a day after I finished it. :-/ It's good news that I just have to rewrite search.

**Comment by wouterel** [comment]
Sounds good. I was curious to know if you were working on this. I'll keep my eyes on this page.

**Comment by subogero** [comment]
Just updated https://github.com/subogero/u2b with search no more depending on the obsolete v2 API. Remotepi integration coming very soon.

**Comment by subogero** [comment]
Updated `master` to use the latest u2b's `WWW::U2B` API for YouTube. Can you test before I create the Debian packages? You need to `make install` the newest u2b before.

**Comment by wouterel** [comment]
I'll try to do that this weekend (not sure how much time I need to merge your new master with my own modifications).

**Comment by subogero** [comment]
With `make itest` you can install a second instance of remotepi, running from the repo's directory. The workflow is easier too: just reload the app in the browser after changes, or `make restart` if you change `api.pl`. The test version is available at `http://host/testpi/`.

You could use that to test another clone of the repo, as well.

**Comment by subogero** [comment]
remotepi 1.4 is out, using u2b 0.1 and omxd 1.5. Deb packages in `deb linux.subogero.com/deb/ /`.

YouTube is back.

**Comment by subogero** [comment]
@wouterel, was it you, running remotepi with Nginx? What are your thoughts about a standalone webserver included in remotepi on a different port? Still could be fronted by Nginx as a reverse proxy on port 80 I guess?

**Comment by wouterel** [comment]
Yes, that was me. I would only do this if it has a distinct advantage. I guess that would be ease-of-installation? Or are there other reasons? It would add another place where security vulnerabilities could occur so one should be careful.

Wouter.

On 10 Jun 2015, at 13:51 , SZAB� Gergely <notifications@github.com<mailto:notifications@github.com>> wrote:


@wouterel<https://github.com/wouterel>, was it you, running remotepi with Nginx? What are your thoughts about a standalone webserver included in remotepi on a different port? Still could be fronted by Nginx as a reverse proxy on port 80 I guess?

�

**Comment by subogero** [comment]
Yes, exactly. I want automatic setup without manual config by the user. But now it's Apache only, it's messy and it's not for everyone. A standalone server would be the best of both worlds here.

On the security side, remotepi has no auth at all, assuming a protected home LAN. All it does is some sanity checks on the input URLs and data.
